#!/bin/bash
hostnamectl set-hostname thinknyx-control-plane && bash
swapoff -a

cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.ipv4.ip_forward = 1
EOF

sysctl --system

apt-get update && apt-get install -y software-properties-common curl

KUBERNETES_VERSION=v1.30 && PROJECT_PATH=prerelease:/main

curl -fsSL https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/$PROJECT_PATH/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/$PROJECT_PATH/deb/ /" | tee /etc/apt/sources.list.d/cri-o.list

apt-get update && apt-get install kubeadm kubelet cri-o -y

kubeadm version && kubelet version && crio --version
systemctl start crio.service
crictl ps
## =================================================
kubeadm completion bash > kubeadm.sh && echo source /etc/bash_completion >> ~/.bashrc && echo source kubeadm.sh >> ~/.bashrc
source ~/.bashrc
kubeadm init --apiserver-advertise-address hostname -i | awk '{print $1}' --pod-network-cidr 10.10.0.0/16 --service-cidr 20.20.0.0/16 --service-dns-domain thinknyx.org
echo export KUBECONFIG=/etc/kubernetes/admin.conf >> ~/.bashrc && source ~/.bashrc && crictl ps
apt-get install -y kubectl && kubectl get nodes

kubectl completion bash >> kubectl.sh && echo source kubectl.sh >> ~/.bashrc && source ~/.bashrc
## ===========================================
curl https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml -O
kubectl apply -f calico.yaml && crictl ps
