####how to create a secret 
 401  vi secret.yml
 #####################
apiVersion: v1 
kind: Secret
metadata:
  name: my-db-password
type: Opaque 
data:
  password: ZGJwYXNzd29yZDEx
########################################
  402  kubectl apply -f secret.yml
  403  kubectl get secret
  404  kubectl describe secret my-db-password
